src/main/java/com/shootdoori/match/controller/TeamController.java, src/main/java/com/shootdoori/match/dto/CreateTeamRequestDto.java, src/main/java/com/shootdoori/match/dto/CreateTeamResponseDto.java, src/main/java/com/shootdoori/match/dto/TeamDetailResponseDto.java, src/main/java/com/shootdoori/match/dto/TeamMapper.java, src/main/java/com/shootdoori/match/entity/SkillLevel.java, src/main/java/com/shootdoori/match/entity/Team.java, src/main/java/com/shootdoori/match/entity/TeamType.java, src/main/java/com/shootdoori/match/entity/User.java, src/main/java/com/shootdoori/match/exception/CaptainNotFoundException.java, src/main/java/com/shootdoori/match/exception/TeamNotFoundException.java, src/main/java/com/shootdoori/match/repository/TeamRepository.java, src/main/java/com/shootdoori/match/service/MatchCompleteService.java, src/main/java/com/shootdoori/match/service/TeamService.java, src/main/java/com/shootdoori/match/service/TeamServiceImpl.java
❌ 
---
- **팀 생성 API (POST /api/teams)** 구현  
- `CreateTeamRequestDto`, `CreateTeamResponseDto` 추가  
- `TeamMapper`를 통해 DTO ↔ Entity 변환 처리  
- `TeamService` → `TeamRepository`를 통한 저장 로직 구현  
- 생성 성공 시 `teamId`, `message`, `teamUrl` 반환
- **팀 단건 조회 API (GET /api/teams/{id})** 구현  
- `TeamDetailResponseDto` 추가  
- `TeamService - findById` 로직에서 존재하지 않는 경우 예외 처리  
- 응답에 `id, name, description, university, skillLevel, teamType, memberCount, createdAt` 포함
- **팀 삭제 API (DELETE /api/teams/{id})** 구현  
- `TeamService - delete` 추가  
- 존재하지 않는 팀일 경우 예외 발생 처리  
- 성공 시 `204 No Content` 반환
- **공통 작업**  
- `Team` 엔티티에 `@PrePersist`, `@PreUpdate` 추가하여 `createdAt`, `updatedAt` 자동 관리  
- `TeamType`, `SkillLevel` enum과 `from(String)` 메서드로 문자열 변환 처리
---
❌ 
---
---
- Exception이 좀 많이 세분화될 것으로 예상이 되는데, 이것도 심상을 …
=> 팀 생성/단건 조회/삭제 기능 구현

src/main/java/com/shootdoori/match/entity/Team.java, src/main/java/com/shootdoori/match/exception/DuplicateMemberException.java, src/main/java/com/shootdoori/match/exception/DuplicatedMemberException.java, src/test/java/com/shootdoori/team/TeamServiceTest.java, src/test/java/com/shootdoori/team/TeamTest.java
❌ 
---
- Team 테스트 코드
- Team domain 테스트 작성
- TeamService 단위 테스트 작성 
- `DuplicatedMemberException` 이름 통일
---
❌ 
---
---
- 서비스를 단위 테스트 형식으로 짜봤는데, 괜찮은지 봐주세요!
---
=> test(team): 팀 도메인 & 팀 서비스 테스트

src/main/java/com/shootdoori/match/entity/Team.java, src/main/java/com/shootdoori/match/exception/DuplicateMemberException.java, src/main/java/com/shootdoori/match/exception/DuplicatedMemberException.java, src/test/java/com/shootdoori/team/TeamServiceTest.java, src/test/java/com/shootdoori/team/TeamTest.java, src/test/java/com/shootdoori/teamMember/TeamMemberServiceTest.java, src/test/java/com/shootdoori/teamMember/teamMemberTest.java
❌ 
---
- TeamMember 테스트 코드
- TeamMember domain 테스트 작성
- TeamMemberService 단위 테스트 작성 
- TeamService 테스트에서 사용되지 않는 변수 제거
---
---
---
- 서비스를 단위 테스트 형식으로 짜봤는데, 괜찮은지 봐주세요!
---
=> test(team): 팀 멤버 도메인 & 팀 멤버 서비스 테스트

src/main/java/com/shootdoori/match/controller/JoinWaitingController.java, src/main/java/com/shootdoori/match/dto/JoinWaitingMapper.java, src/main/java/com/shootdoori/match/entity/Team.java, src/main/java/com/shootdoori/match/exception/ErrorCode.java, src/main/java/com/shootdoori/match/repository/JoinWaitingRepository.java, src/main/java/com/shootdoori/match/service/JoinWaitingService.java, src/test/java/com/shootdoori/joinWaiting/JoinWaitingE2ETest.java, src/test/java/com/shootdoori/joinWaiting/JoinWaitingServiceTest.java
❌ 
---
- 사용자별 가입 신청 페이지 조회 구현 (대기중/거절 상태) & 테스트 코드 작성
- 서비스 단위 테스트 작성
- E2E 테스트 작성
---
❌ 
---
---
❌ 
---
=> feat(join-waiting): 사용자별 가입 신청 페이지 조회 구현 & 테스트 코드 작성

.github/workflows/main.yml, appspec.yml, scripts/deploy.sh
❌ 
---
- MySQL 배포 환경 설정
---
❌ 
---
---
❌ 
---
=> feat: MySQL 배포 환경 설정

src/main/java/com/shootdoori/match/config/SecurityConfig.java, src/test/java/com/shootdoori/joinWaiting/JoinWaitingE2ETest.java
❌ 
---
- MySQL 배포 환경 설정 및 JWT 인증 테스트 개선
---
❌ 
---
---
❌ 
---
=> chore: MySQL 배포 환경 설정 및 JWT 인증 테스트 개선

src/test/java/com/shootdoori/match/auth/AuthTest.java
❌ 
---
AuthTest 격리 및 401/중복 오류 수정
---
❌ 
---
---
❌ 
---
=> fix(test): AuthTest 격리 및 401/중복 오류 수정

src/test/java/com/shootdoori/match/auth/AuthTest.java
❌ 
---
- Logout/탈퇴 테스트에서 불필요한 flush/clear 제거
---
❌ 
---
---
❌ 
---
=> test: Logout/탈퇴 테스트에서 불필요한 flush/clear 제거

build.gradle, src/main/java/com/shootdoori/match/controller/LoginController.java, src/main/resources/application-test.properties, src/test/java/com/shootdoori/match/auth/AuthTest.java
❌ 
---
- refreshToken 만료 시 null Cookie 값으로 발생한 IllegalArgumentException 수정
---
❌ 
---
---
❌ 
---
=> fix(auth): refreshToken 만료 시 null Cookie 값으로 발생한 IllegalArgumentException 수정

build.gradle, src/main/java/com/shootdoori/match/controller/LoginController.java, src/main/resources/application-test.properties, src/test/java/com/shootdoori/match/auth/AuthTest.java
❌ 
---
- 인증 테스트 실패 지점 출력하도록 수정
---
❌ 
---
---
❌ 
---
=> test(auth): 인증 테스트 실패 지점 출력하도록 수정

build.gradle, src/main/java/com/shootdoori/match/controller/LoginController.java
❌ 
---
- 리프레시 토큰 만료시 코드 수정 & Gradle 테스트 로깅 상세화
---
❌ 
---
---
❌ 
---
=> test(auth): 리프레시 토큰 만료시 코드 수정 & Gradle 테스트 로깅 상세화

.github/workflows/main.yml
❌ 
---
- S3_BUCKET 따옴표/공백 제거로 버킷명 오류 수정
---
❌ 
---
---
❌ 
---
=> chore(ci): S3_BUCKET 따옴표/공백 제거로 버킷명 오류 수정

scripts/deploy.sh
❌ 
---
-  .env 로딩 오류 해결과 배포 스크립트 안정화 (`deploy.sh` 수정)
---
❌ 
---
---
❌ 
---
=> fix(deploy): .env 로딩 오류 해결과 배포 스크립트 안정화

.github/workflows/main.yml
❌ 
---
- .env 작성 관련 코드 수정
---
❌ 
---
---
❌ 
---
=> fix(deploy): .env 작성 관련 코드 수정

.github/workflows/main.yml, src/main/resources/application.properties
❌ 
---
- 메일 테스트 실패 해결 위한 secrets 값 추가
---
❌ 
---
---
❌ 
---
=> chore: 메일 테스트 실패 해결 위한 secrets 값 추가

src/main/resources/application-dev.properties, src/main/resources/application-prod.properties, src/main/resources/application-test.properties, src/main/resources/application.properties, src/test/java/com/shootdoori/match/service/MailServiceTest.java
❌ 
---
- mailServiceTest를 통합테스트에서 단위테스트로 변경
- CI를 위한 mail 환경 변수값 세팅
---
❌ 
---
---
❌ 
---
=> chore: mailServiceTest를 통합테스트에서 단위테스트로 변경 & mail 환경 변수값 세팅

src/main/java/com/shootdoori/match/controller/TeamMemberController.java, src/main/java/com/shootdoori/match/entity/TeamMemberRole.java, src/main/java/com/shootdoori/match/service/TeamMemberService.java, src/test/java/com/shootdoori/teamMember/TeamMemberServiceTest.java
❌ 
---
- 팀원 역할 수정/탈퇴 서비스 코드 변경 & 서비스 단위 테스트 추가
- 팀원 강제 추방 기능 추가 & 서비스 단위 테스트 추가
---
❌ 
---
---
❌ 
---
=> refactor(team-member): 팀원 역할 수정/탈퇴 서비스 코드 변경 & 팀원 강제 추방 기능 추가 & 서비스 단위 테스트 추가

src/main/java/com/shootdoori/match/controller/HealthController.java, src/main/resources/templates/main.html, src/main/resources/templates/privacy/delete.html
❌ 
---
- 계정 삭제 요청 페이지 추가 및 `HealthController`로 이름 변경
---
❌ 
---
---
❌ 
---
=> feat: 계정 삭제 요청 페이지 추가 및 `HealthController`로 이름 변경

src/test/java/com/shootdoori/match/service/MatchRequestServiceTest.java
X
---
- MatchRequestServiceTest 코드에서 로컬에서 테스트 통과되지만, CI 환경에서 실패하는 문제 해결
---
X
---
---
X
---
=> fix(test-match-request-service) : 107 branch 머지후 CI 테스트 코드 에러 해결

src/main/java/com/shootdoori/match/config/SecurityConfig.java, src/main/java/com/shootdoori/match/controller/VenueController.java
❌ 
---
슛두리 앱에서 경기장 조회 API 정근 불가한 문제 해결
---
❌ 
---
---
❌ 
---
=> fix(venue): 경기장 조회 API 접근 불가 해결
